src/catalog/catalog/urls.py
# pylint: disable=C0114.C0115,C0116
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


class MainPageView(TemplateView):
    template_name = 'index.html'

urlpatterns = [
    path('products/', include('products.urls')),
    path('admin/', admin.site.urls),
    path('', MainPageView.as_view(), name='index'),
]

src/catalog/products/urls.py
# pylint: disable=C0114,C0115,C0116
from django.urls import path

from . import views

urlpatterns = [
    path('projects', views.index, name='index'),
    path('project/<int:project_id>/', views.project_detail, name='project_detail'),
    path('journey/<int:journey_id>/', views.journey_detail, name='journey_detail'),
]

src/catalog/products/models.py
# pylint: disable=C0114,C0115,C0116
from django.db import models


class Journey(models.Model):
    name = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    family = models.CharField(max_length=20)  # web, mobile, headless

    def __str__(self):
        return str(self.name)


class Feature(models.Model):
    journey = models.ForeignKey(Journey, on_delete=models.CASCADE)

    name = models.CharField(max_length=200)
    modelbank = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.journey.name}::{self.name}'


class SubFeature(models.Model):
    feature = models.ForeignKey(Feature, on_delete=models.CASCADE)

    name = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.feature.name}-{self.name}'


class Assignee(models.Model):
    journeys = models.ManyToManyField(Journey, blank=True)

    name = models.CharField(max_length=200)

    def __str__(self):
        return str(self.name)


class Team(models.Model):
    journeys = models.ManyToManyField(Journey, blank=True)

    name = models.CharField(max_length=50)

    def __str__(self):
        return str(self.name)


class Project(models.Model):
    journeys = models.ManyToManyField(Journey, blank=True)

    name = models.CharField(max_length=200)
    key = models.CharField(max_length=20)
    counter = models.IntegerField()

    def __str__(self):
        return str(self.name)


class Vendor(models.Model):
    journeys = models.ManyToManyField(Journey, blank=True)

    name = models.CharField(max_length=200)

    def __str__(self):
        return str(self.name)


class Version(models.Model):
    journeys = models.ManyToManyField(Journey, through='Release', blank=True)

    name = models.CharField(max_length=200)

    def __str__(self):
        return str(self.name)


class Release(models.Model):
    journey = models.ForeignKey(Journey, on_delete=models.DO_NOTHING, blank=True, null=True)
    version = models.ForeignKey(Version, on_delete=models.DO_NOTHING, blank=True, null=True)

    release_date = models.DateField()

src/catalog/products/views.py
# pylint: disable=C0114,C0115,C0116
from django.shortcuts import render, get_object_or_404

from .models import Journey, Project


def index(request):
    projects = Project.objects.order_by('key')  # pylint: disable=E1101
    ctx = {'projects': projects}
    return render(request, 'products/index.html', ctx)

def project_detail(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    return render(request, 'products/project_detail.html', {'project': project})


def journey_list(request):
    journeys = Journey.objects.order_by('-pub_date')[:5]  # pylint: disable=E1101
    ctx = {'journeys': journeys}
    return render(request, 'products/journey_list.html', ctx)

def journey_detail(request, journey_id):
    journey = get_object_or_404(Journey, pk=journey_id)
    return render(request, 'products/journey_detail.html', {'journey': journey})

src/catalog/templates/index.html
{% extends "layout.html" %}

{% block content %}

<h1 class="title">R&D Product Catalog</h1>

<p>
<ul>
	<li><a href="http://127.0.0.1:5050">PgAdmin</a></li>
</ul>

{% endblock %}

src/catalog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
    {% block title %}
    R&D Product Catalog
    {% endblock %}
    </title>
    {% block script %}
    <script></script>
    {% endblock %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>
  <body>
  <section class="section">
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </section>
  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <a href="/products/projects">Projects</a> |
        <a href="#">Metrics</a> |
        <a href="/search/">Search</a> |
        <a href="/admin">Admin</a>
      </p>
    </div>
  </footer>
  </body>
</html>

src/catalog/templates/products/index.html
{% extends "layout.html" %}

{% block content %}

<h1 class="title">Projects</h1>
<p class="subtitle">Value stream.</p>

{% if projects %}
    <ul>
    {% for p in projects %}
        <li>Project: <a href="{% url 'project_detail' p.id %}">{{ p.name }} | {{ p.key }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No projects are available.</p>
{% endif %}

{% endblock %}

src/catalog/templates/products/journey_detail.html
{% extends "layout.html" %}

{% block content %}

<h1 class="title">{{ journey.name }}</h1>
<p class="subtitle">Details of the journey.</p>

<ul>
{% for feature in journey.feature_set.all %}
    <li>Feature: <span class="has-text-weight-bold">{{ feature.name }}</span></li>

    <ul>
    {% for subfeature in feature.subfeature_set.all %}
    <li>Subfeature: <span class="has-text-info">{{ subfeature.name }}</span></li>
    {% endfor %}
    </ul>
    <br/>
{% endfor %}
</ul>

Family: {{ journey.family }}<br/>
Vendor: {{ journey.vendor_set.first }}<br/>
Owner: {{ journey.owner_set.first }}<br/>
Team: {{ journey.team_set.first }}<br/>

{% endblock %}

src/catalog/templates/products/journey_list.html
{% extends "layout.html" %}

{% block content %}

<h1 class="title">Journeys</h1>
<p class="subtitle">A set of logically grouped banking functionality.</p>

{% if journeys %}
    <ul>
    {% for j in journeys %}
        <li>Journey: <a href="{% url 'journey_detail' j.id %}">{{ j.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No journeys are available.</p>
{% endif %}

{% endblock %}

src/catalog/templates/products/project_detail.html
{% extends "layout.html" %}

{% block content %}

<h1 class="title">{{ project.name }}</h1>
<p class="subtitle">List of journeys.</p>

<ul>
{% for journey in project.journeys.all %}
    <li>Journey: <span class="has-text-weight-bold">{{ journey.name }}</span></li>

    <ul>
    {% for feature in journey.feature_set.all %}
    <li>Feature: <span class="has-text-info">{{ feature.name }}</span></li>
    {% endfor %}
    </ul>
    <br/>
{% endfor %}
</ul>

Key: {{ project.key }}<br/>
Counter: {{ project.counter }}<br/>

{% endblock %}